class AuthzFile

  PREAMBLE = "# This file is generated by the code@berkeley application\n[/]".freeze
  PERMISSIONS = { :commit => 'rw', :read => 'r' }.freeze

  def initialize
    @entries = [PREAMBLE]
  end

  def append_committers(committers)
    committers.each { |committer| @entries << entry(committer.username, :commit) }
  end

  def append_readers(readers)
    readers.each { |reader| @entries << entry(reader.username, :read) }
  end

  def to_s
    @entries.flatten.uniq.join("\n")
  end

  private

  def entry(username, perm)
    "#{username} = #{permission(perm)}"
  end

  def permission(perm)
    PERMISSIONS.fetch(perm.to_sym)
  end

end

