class UcbAffiliation
  STAFF                  = "EMPLOYEE-TYPE-STAFF"
  FACULTY                = "EMPLOYEE-TYPE-FACULTY"
  ACADEMIC               = "EMPLOYEE-TYPE-ACADEMIC"
  CONTRACTOR             = "AFFILIATE-TYPE-CONTRACTOR"
  CONSULTANT             = "AFFILIATE-TYPE-CONSULTANT"
  INDEPENDENT_CONTRACTOR = "AFFILIATE-TYPE-INDEPENDENT CONTRACTOR"
  TEMPORARY_AGENCY_STAFF = "AFFILIATE-TYPE-TEMPORARY AGENCY STAFF"

  def self.all
    [STAFF, FACULTY, ACADEMIC, CONSULTANT, CONTRACTOR, INDEPENDENT_CONTRACTOR, TEMPORARY_AGENCY_STAFF]
  end
end